### PR TITLE
Increase optimizer steps

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
```
·-----------------------------------------------------------------|---------------------------|----------------|-----------------------------·
|                       Solc version: 0.8.6                       ·  Optimizer enabled: true  ·  Runs: 100000  ·  Block limit: 12450000 gas  │
··································································|···························|················|······························
|  Methods                                                                                                                                   │
····························|·····································|·············|·············|················|···············|··············
|  Contract                 ·  Method                             ·  Min        ·  Max        ·  Avg           ·  # calls      ·  eur (avg)  │
····························|·····································|·············|·············|················|···············|··············
|  AavePoolMock             ·  deposit                            ·      55543  ·     106915  ·        106307  ·          178  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  AavePoolMock             ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·         26593  ·            4  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  AavePoolMock             ·  setLiquidityIndex                  ·      26595  ·      26607  ·         26602  ·           68  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  AaveTempusPool           ·  finalize                           ·          -  ·          -  ·         51127  ·           38  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  AaveTempusPool           ·  setFeesConfig                      ·      48443  ·      88411  ·         55112  ·           12  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  BalancerPoolToken        ·  approve                            ·      26255  ·      46285  ·         42778  ·         1624  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  BalancerPoolToken        ·  transfer                           ·      51443  ·      61701  ·         59668  ·          214  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  CErc20                   ·  approve                            ·      26255  ·      46215  ·         45988  ·          182  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  CErc20                   ·  mint                               ·      59182  ·     110554  ·        109946  ·          178  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  CErc20                   ·  transfer                           ·      51435  ·      51447  ·         51442  ·          172  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  CompoundTempusPool       ·  finalize                           ·          -  ·          -  ·         54140  ·           38  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  CompoundTempusPool       ·  setFeesConfig                      ·      48455  ·      88327  ·         55100  ·           12  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ComptrollerMock          ·  enterMarkets                       ·      25307  ·      89875  ·         89158  ·          180  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ComptrollerMock          ·  exitMarket                         ·          -  ·          -  ·         17497  ·            2  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ComptrollerMock          ·  setExchangeRate                    ·      26508  ·      26568  ·         26535  ·           68  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ComptrollerMock          ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·         43605  ·            4  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20FixedSupply         ·  approve                            ·      46166  ·      46250  ·         46211  ·          574  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20FixedSupply         ·  transfer                           ·      28685  ·      51481  ·         51310  ·          546  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20OwnerMintableToken  ·  approve                            ·      14528  ·      46239  ·         40527  ·           26  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20OwnerMintableToken  ·  burn                               ·          -  ·          -  ·         33729  ·            1  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20OwnerMintableToken  ·  burnFrom                           ·          -  ·          -  ·         17128  ·            2  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20OwnerMintableToken  ·  mint                               ·      68417  ·      68429  ·         68426  ·           31  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20Vesting             ·  claim                              ·      52148  ·      86372  ·         74231  ·            8  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20Vesting             ·  claim                              ·      70869  ·      86112  ·         78491  ·            2  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20Vesting             ·  startVesting                       ·     103342  ·     120454  ·        119378  ·           16  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20Vesting             ·  startVestingBatch                  ·          -  ·          -  ·        202129  ·            1  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20Vesting             ·  stopVesting                        ·      21369  ·      21448  ·         21422  ·            3  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  ERC20Vesting             ·  transferVesting                    ·      64976  ·      72676  ·         67543  ·            3  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  _setSharesAndEthBalance            ·      16104  ·      68188  ·         41094  ·           43  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  approve                            ·      26299  ·      46295  ·         46064  ·           91  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  depositBufferedEther               ·          -  ·          -  ·         23625  ·            1  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  depositBufferedEther               ·      68548  ·      83548  ·         78548  ·            3  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  pushBeacon                         ·          -  ·          -  ·         59375  ·            2  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·         43628  ·            3  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  submit                             ·      42241  ·      93278  ·         91112  ·           94  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  transfer                           ·      58698  ·      58710  ·         58701  ·           86  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoMock                 ·  withdraw                           ·          -  ·          -  ·         30956  ·            1  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoTempusPool           ·  finalize                           ·      48957  ·      53611  ·         53366  ·           19  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  LidoTempusPool           ·  setFeesConfig                      ·      48479  ·      88411  ·         55136  ·            6  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  OwnableMock              ·  acceptOwnership                    ·          -  ·          -  ·         18041  ·            2  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  OwnableMock              ·  transferOwnership                  ·          -  ·          -  ·         47655  ·            3  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusAMM                ·  approve                            ·      26300  ·      46320  ·         41311  ·           56  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusAMM                ·  startAmplificationParameterUpdate  ·      30928  ·      30939  ·         30932  ·           98  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusAMM                ·  stopAmplificationParameterUpdate   ·          -  ·          -  ·         30872  ·            7  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  depositAndFix                      ·     242527  ·     313325  ·        273145  ·           21  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  depositAndProvideLiquidity         ·     316549  ·     412019  ·        341092  ·           28  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  depositBacking                     ·     116589  ·     252172  ·        198588  ·           34  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  depositYieldBearing                ·      67840  ·     202334  ·        159927  ·          567  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  exitTempusAMM                      ·     218433  ·     226436  ·        222768  ·            7  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  exitTempusAmmAndRedeem             ·     231302  ·     512864  ·        347389  ·           27  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  exitTempusAMMAndRedeem             ·     270815  ·     312082  ·        288449  ·           13  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  provideLiquidity                   ·     241259  ·     252645  ·        247512  ·            7  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  redeemToBacking                    ·      61718  ·     103229  ·         83387  ·            8  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  redeemToYieldBearing               ·      50920  ·      83759  ·         64846  ·          112  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  register                           ·      14616  ·      46355  ·         45008  ·          165  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusController         ·  transferFees                       ·      43532  ·      64251  ·         52541  ·           14  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusToken              ·  burn                               ·          -  ·          -  ·         53783  ·            1  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusToken              ·  mint                               ·      77034  ·      94134  ·         88434  ·            3  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  TempusToken              ·  transfer                           ·          -  ·          -  ·         55991  ·            1  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  Vault                    ·  exitPool                           ·     161649  ·     231982  ·        192254  ·           28  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  Vault                    ·  joinPool                           ·     184214  ·     342270  ·        283140  ·          343  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  Vault                    ·  swap                               ·     128440  ·     150232  ·        139541  ·          308  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnTempusPool          ·  finalize                           ·          -  ·          -  ·         48787  ·           38  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnTempusPool          ·  setFeesConfig                      ·      48443  ·      88411  ·         55112  ·           12  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnVaultMock           ·  approve                            ·      26288  ·      46284  ·         46031  ·          182  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnVaultMock           ·  deposit                            ·      97615  ·      97675  ·         97644  ·          168  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnVaultMock           ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·         43656  ·            4  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnVaultMock           ·  setPricePerShare                   ·      26518  ·      26566  ·         26547  ·           60  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  YearnVaultMock           ·  transfer                           ·      51422  ·      51482  ·         51451  ·          172  ·          -  │
····························|·····································|·············|·············|················|···············|··············
|  Deployments                                                    ·                                            ·  % of limit   ·             │
··································································|·············|·············|················|···············|··············
|  AavePoolMock                                                   ·    2274424  ·    2294456  ·       2294102  ·       18.4 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  AaveTempusPool                                                 ·    5047865  ·    5047911  ·       5047902  ·       40.5 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  Authorizer                                                     ·          -  ·          -  ·        758911  ·        6.1 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  CErc20                                                         ·    1564216  ·    1564288  ·       1564252  ·       12.6 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  CompoundTempusPool                                             ·    5255779  ·    5300189  ·       5275609  ·       42.4 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  ComptrollerMock                                                ·     496364  ·     516372  ·        516171  ·        4.1 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  ERC20FixedSupply                                               ·     790792  ·     790900  ·        790846  ·        6.4 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  ERC20OwnerMintableToken                                        ·          -  ·          -  ·       1063978  ·        8.5 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  ERC20Vesting                                                   ·    1653255  ·    1653267  ·       1653267  ·       13.3 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  LidoMock                                                       ·          -  ·          -  ·       1361314  ·       10.9 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  LidoTempusPool                                                 ·    4979247  ·    4983937  ·       4979811  ·         40 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  OwnableMock                                                    ·          -  ·          -  ·        305598  ·        2.5 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  Stats                                                          ·          -  ·          -  ·       1852725  ·       14.9 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  TempusAMM                                                      ·    4925021  ·    4925165  ·       4925091  ·       39.6 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  TempusController                                               ·          -  ·          -  ·       4519803  ·       36.3 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  TempusToken                                                    ·          -  ·          -  ·       2672167  ·       21.5 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  Vault                                                          ·    6015093  ·    6015105  ·       6015098  ·       48.3 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  YearnTempusPool                                                ·    4922240  ·    4922372  ·       4922320  ·       39.5 %  ·          -  │
··································································|·············|·············|················|···············|··············
|  YearnVaultMock                                                 ·    1277291  ·    1297263  ·       1297063  ·       10.4 %  ·          -  │
·-----------------------------------------------------------------|-------------|-------------|----------------|---------------|-------------·
```

**Comment by axic** [comment]
```
·-----------------------------------------------------------------|---------------------------|--------------|-----------------------------·
|                      Solc version: 0.8.10                       ·  Optimizer enabled: true  ·  Runs: 1000  ·  Block limit: 12450000 gas  │
··································································|···························|··············|······························
|  Methods                                                                                                                                 │
····························|·····································|·············|·············|··············|···············|··············
|  Contract                 ·  Method                             ·  Min        ·  Max        ·  Avg         ·  # calls      ·  eur (avg)  │
····························|·····································|·············|·············|··············|···············|··············
|  AavePoolMock             ·  deposit                            ·      55691  ·     107063  ·      106461  ·          180  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  AavePoolMock             ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·       26608  ·            4  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  AavePoolMock             ·  setLiquidityIndex                  ·      26595  ·      26607  ·       26603  ·           70  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  AaveTempusPool           ·  finalize                           ·          -  ·          -  ·       51035  ·           38  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  AaveTempusPool           ·  setFeesConfig                      ·      48455  ·      88423  ·       55124  ·           12  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  BalancerPoolToken        ·  approve                            ·      26303  ·      46333  ·       42830  ·         1626  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  BalancerPoolToken        ·  transfer                           ·      51527  ·      61705  ·       59706  ·          216  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  CErc20                   ·  approve                            ·      26303  ·      46263  ·       46038  ·          184  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  CErc20                   ·  mint                               ·      59110  ·     110482  ·      109880  ·          180  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  CErc20                   ·  transfer                           ·      51519  ·      51531  ·       51526  ·          174  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  CompoundTempusPool       ·  finalize                           ·          -  ·          -  ·       53908  ·           38  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  CompoundTempusPool       ·  setFeesConfig                      ·      48467  ·      88339  ·       55112  ·           12  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ComptrollerMock          ·  enterMarkets                       ·      25334  ·      89920  ·       89210  ·          182  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ComptrollerMock          ·  exitMarket                         ·          -  ·          -  ·       17530  ·            2  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ComptrollerMock          ·  setExchangeRate                    ·      26508  ·      26568  ·       26535  ·           70  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ComptrollerMock          ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·       43608  ·            4  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20FixedSupply         ·  approve                            ·      46214  ·      46298  ·       46259  ·          580  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20FixedSupply         ·  transfer                           ·      28769  ·      51565  ·       51396  ·          552  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20OwnerMintableToken  ·  approve                            ·      14552  ·      46287  ·       40574  ·           26  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20OwnerMintableToken  ·  burn                               ·          -  ·          -  ·       33789  ·            1  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20OwnerMintableToken  ·  burnFrom                           ·          -  ·          -  ·       17164  ·            2  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20OwnerMintableToken  ·  mint                               ·      68477  ·      68489  ·       68486  ·           31  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20Vesting             ·  claim                              ·      52289  ·      86513  ·       74371  ·            8  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20Vesting             ·  claim                              ·      71010  ·      86256  ·       78633  ·            2  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20Vesting             ·  startVesting                       ·     103624  ·     120736  ·      119660  ·           16  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20Vesting             ·  startVestingBatch                  ·          -  ·          -  ·      202705  ·            1  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20Vesting             ·  stopVesting                        ·      21429  ·      21508  ·       21482  ·            3  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  ERC20Vesting             ·  transferVesting                    ·      65060  ·      72760  ·       67627  ·            3  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  _setSharesAndEthBalance            ·      16104  ·      68188  ·       40980  ·           44  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  approve                            ·      26347  ·      46343  ·       46114  ·           92  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  depositBufferedEther               ·          -  ·          -  ·       23625  ·            1  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  depositBufferedEther               ·      68557  ·      83557  ·       78557  ·            3  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  pushBeacon                         ·          -  ·          -  ·       59423  ·            2  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·       43631  ·            3  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  submit                             ·      42292  ·      93326  ·       91183  ·           95  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  transfer                           ·      58797  ·      58809  ·       58800  ·           87  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoMock                 ·  withdraw                           ·          -  ·          -  ·       30995  ·            1  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoTempusPool           ·  finalize                           ·      48841  ·      53498  ·       53253  ·           19  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  LidoTempusPool           ·  setFeesConfig                      ·      48491  ·      88423  ·       55148  ·            6  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  OwnableMock              ·  acceptOwnership                    ·          -  ·          -  ·       18083  ·            2  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  OwnableMock              ·  transferOwnership                  ·          -  ·          -  ·       47718  ·            3  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusAMM                ·  approve                            ·      26300  ·      46320  ·       41311  ·           56  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusAMM                ·  startAmplificationParameterUpdate  ·      30928  ·      30939  ·       30932  ·           98  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusAMM                ·  stopAmplificationParameterUpdate   ·          -  ·          -  ·       30872  ·            7  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  depositAndFix                      ·     240477  ·     309878  ·      270783  ·           21  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  depositAndProvideLiquidity         ·     315254  ·     409324  ·      338093  ·           28  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  depositBacking                     ·     116522  ·     251678  ·      198424  ·           34  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  depositYieldBearing                ·      67815  ·     202087  ·      159983  ·          574  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  exitTempusAMM                      ·     217015  ·     224554  ·      221247  ·            7  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  exitTempusAmmAndRedeem             ·     229008  ·     512146  ·      343405  ·           27  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  exitTempusAMMAndRedeem             ·     267653  ·     307750  ·      285089  ·           13  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  provideLiquidity                   ·     240408  ·     251120  ·      246453  ·            7  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  redeemToBacking                    ·      61691  ·     102382  ·       83049  ·            8  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  redeemToYieldBearing               ·      50387  ·      82956  ·       63697  ·          119  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  register                           ·      14641  ·      46406  ·       45058  ·          165  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusController         ·  transferFees                       ·      43787  ·      64426  ·       52775  ·           14  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusToken              ·  burn                               ·          -  ·          -  ·       53915  ·            1  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusToken              ·  mint                               ·      77217  ·      94317  ·       88617  ·            3  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  TempusToken              ·  transfer                           ·          -  ·          -  ·       56111  ·            1  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  Vault                    ·  exitPool                           ·     161154  ·     229962  ·      191273  ·           28  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  Vault                    ·  joinPool                           ·     183176  ·     341431  ·      282524  ·          343  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  Vault                    ·  swap                               ·     127342  ·     148283  ·      138233  ·          308  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnTempusPool          ·  finalize                           ·          -  ·          -  ·       48671  ·           38  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnTempusPool          ·  setFeesConfig                      ·      48455  ·      88423  ·       55124  ·           12  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnVaultMock           ·  approve                            ·      26336  ·      46332  ·       46082  ·          184  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnVaultMock           ·  deposit                            ·      97682  ·      97742  ·       97711  ·          170  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnVaultMock           ·  setFailNextDepositOrRedeem         ·          -  ·          -  ·       43659  ·            4  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnVaultMock           ·  setPricePerShare                   ·      26518  ·      26566  ·       26547  ·           62  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  YearnVaultMock           ·  transfer                           ·      51506  ·      51566  ·       51535  ·          174  ·          -  │
····························|·····································|·············|·············|··············|···············|··············
|  Deployments                                                    ·                                          ·  % of limit   ·             │
··································································|·············|·············|··············|···············|··············
|  AavePoolMock                                                   ·    1897444  ·    1917476  ·     1917125  ·       15.4 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  AaveTempusPool                                                 ·    4369282  ·    4369376  ·     4369361  ·       35.1 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  Authorizer                                                     ·          -  ·          -  ·      758911  ·        6.1 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  CErc20                                                         ·    1313071  ·    1313143  ·     1313107  ·       10.5 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  CompoundTempusPool                                             ·    4521017  ·    4565475  ·     4540890  ·       36.5 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  ComptrollerMock                                                ·     420599  ·     440607  ·      440407  ·        3.5 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  ERC20FixedSupply                                               ·     694752  ·     694860  ·      694806  ·        5.6 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  ERC20OwnerMintableToken                                        ·          -  ·          -  ·      905434  ·        7.3 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  ERC20Vesting                                                   ·    1356730  ·    1356742  ·     1356742  ·       10.9 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  LidoMock                                                       ·          -  ·          -  ·     1180307  ·        9.5 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  LidoTempusPool                                                 ·    4296576  ·    4301317  ·     4297183  ·       34.5 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  OwnableMock                                                    ·          -  ·          -  ·      258011  ·        2.1 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  Stats                                                          ·          -  ·          -  ·     1570620  ·       12.6 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  TempusAMM                                                      ·    4925069  ·    4925213  ·     4925139  ·       39.6 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  TempusController                                               ·          -  ·          -  ·     3655693  ·       29.4 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  TempusToken                                                    ·          -  ·          -  ·     2235004  ·         18 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  Vault                                                          ·    6015093  ·    6015105  ·     6015098  ·       48.3 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  YearnTempusPool                                                ·    4241711  ·    4241891  ·     4241833  ·       34.1 %  ·          -  │
··································································|·············|·············|··············|···············|··············
|  YearnVaultMock                                                 ·    1082751  ·    1102723  ·     1102525  ·        8.9 %  ·          -  │
·-----------------------------------------------------------------|-------------|-------------|--------------|---------------|-------------·
```

**Comment by axic** [comment]
Verdict is that prices on the controller go down by 1-4k, which is kind of miniscule.

The code size goes up significantly, for example the controller is 20% more expensive and the pools are around 13-16% more expensive to deploy. They are still around 30-40% of the block gas limit so no issue deploying.

**Review by mijovic — DISMISSED** [review]
I would say let's merge this

**Review by mijovic — APPROVED** [review]

**Pull request merged**
